#!/usr/bin/env bash
#
# build-mlx-swift-lm-fork.sh — regenerate the pre-patched mlx-swift-lm fork
#
# The root Package.swift depends on mlx-swift-lm by URL+revision so that AFMKit
# resolves with NO git submodules (a plain `git clone` + `swift build` works for
# downstream consumers — see docs/afmkit-url-consumption.md). That fork is a
# build-time artifact: it is the upstream `vendor/mlx-swift-lm` submodule with
# `Scripts/patches/` applied and `Package.swift` pinned to mlx-swift 0.30.3.
#
# Run this whenever the patch set (Scripts/patches/) changes. It:
#   1. ensures the submodule is checked out and the patches are applied,
#   2. materializes the patched tree into a fresh clone of the fork,
#   3. commits + pushes if anything changed,
#   4. prints the new revision and the exact Package.swift line to update.
#
# IMPORTANT: the build uses the FORK, not the submodule. Applying patches to the
# submodule (as build-from-scratch.sh does) has NO effect on the build until you
# run this script AND bump the `revision:` in the root Package.swift.
#
# Requirements: gh authenticated with push access to FORK_REMOTE; rsync.
set -euo pipefail

FORK_REMOTE="${FORK_REMOTE:-https://github.com/scouzi1966/mlx-swift-lm.git}"
FORK_BRANCH="${FORK_BRANCH:-main}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUBMODULE="$REPO_ROOT/vendor/mlx-swift-lm"

echo "==> Repo root:   $REPO_ROOT"
echo "==> Fork remote: $FORK_REMOTE (branch $FORK_BRANCH)"

# 1. Submodule present + patches applied -------------------------------------
if [ ! -f "$SUBMODULE/Package.swift" ]; then
  echo "==> Initializing vendor/mlx-swift-lm submodule…"
  git -C "$REPO_ROOT" submodule update --init --recursive --force vendor/mlx-swift-lm
fi
echo "==> Applying patches (Scripts/apply-mlx-patches.sh)…"
"$REPO_ROOT/Scripts/apply-mlx-patches.sh"
if ! "$REPO_ROOT/Scripts/apply-mlx-patches.sh" --check >/dev/null 2>&1; then
  echo "ERROR: patches not fully applied after apply step — aborting." >&2
  exit 1
fi

# 2. Materialize into a fresh clone of the fork ------------------------------
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
echo "==> Cloning fork into $WORK …"
git clone -q --branch "$FORK_BRANCH" --single-branch "$FORK_REMOTE" "$WORK/fork" \
  || git clone -q "$FORK_REMOTE" "$WORK/fork"

# Mirror the patched submodule tree into the fork working copy. --delete keeps
# the fork in lockstep with the submodule (files removed upstream disappear too).
# Never copy git metadata, build output, or the patch .original backups.
rsync -a --delete \
  --exclude='.git' --exclude='.build' --exclude='*.original' \
  "$SUBMODULE/" "$WORK/fork/"

# Re-add the fork-only derivation note (rsync --delete removed it).
cat > "$WORK/fork/AFM-FORK.md" <<'EOF'
# mlx-swift-lm — afm pre-patched fork

Pre-patched fork of [ml-explore/mlx-swift-lm](https://github.com/ml-explore/mlx-swift-lm),
the SwiftPM dependency for **afm** ([scouzi1966/maclocal-api](https://github.com/scouzi1966/maclocal-api)):
upstream + `maclocal-api/Scripts/patches/` applied, `Package.swift` pinned to `mlx-swift` 0.30.3.
Exists so afm resolves by `.package(url:)` with no git submodules.

**Do not edit directly** — regenerated by `maclocal-api/Scripts/build-mlx-swift-lm-fork.sh`.
Upstream license (MIT) retained.
EOF

# 3. Commit + push if changed ------------------------------------------------
cd "$WORK/fork"
git add -A
if git diff --cached --quiet; then
  echo "==> Fork already up to date — no changes to push."
  REV="$(git rev-parse HEAD)"
else
  STAMP="$(git -C "$REPO_ROOT" rev-parse --short HEAD)"
  git -c user.name="afm fork bot" -c user.email="noreply@maclocal-api" \
    commit -q -m "Regenerate from maclocal-api@$STAMP (patches applied, mlx-swift 0.30.3)"
  git push -q origin "$FORK_BRANCH"
  REV="$(git rev-parse HEAD)"
  echo "==> Pushed new fork revision."
fi

# 4. Report ------------------------------------------------------------------
echo ""
echo "============================================================"
echo "Fork revision: $REV"
echo ""
echo "Update the root Package.swift dependency to:"
echo "  .package(url: \"$FORK_REMOTE\", revision: \"$REV\"),"
echo "============================================================"
